{% set name = "mdolab-baseclasses" %}
{% set version = "1.8.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mdolab/baseclasses/archive/refs/tags/v{{ version }}.tar.gz
  sha256: e03865371280d795f080341dea119a7bdcf2acc1aa89599e1b30588633a5c501

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy

test:
  imports:
    - baseclasses
  requires:
    - python {{ python_min }}
    - pip
    - testflo
    - parameterized
  source_files:
    - tests
  commands:
    - pip check
    - testflo . --verbose

about:
  home: https://github.com/mdolab/baseclasses
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.md
  summary: Base classes used with MDO Lab tools.
  doc_url: https://github.com/mdolab/baseclasses/blob/master/README.md
  dev_url: https://github.com/mdolab/baseclasses

extra:
  recipe-maintainers:
    - ewu63
    - eirikurj
    - whophil
