{% set name = "mdolab-baseclasses" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mdolab/baseclasses/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 8819feb8d222fb1da9c99077900b3c274bae873dd65bc7d327b269d5f256bdce

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy

test:
  imports:
    - baseclasses
  requires:
    - pip
    - testflo
    - parameterized
  source_files:
    - tests
  commands:
    - pip check
    - testflo . --verbose

about:
  home: https://github.com/mdolab/baseclasses
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.md
  summary: Base classes used with MDO Lab tools.
  doc_url: https://github.com/mdolab/baseclasses/blob/master/README.md
  dev_url: https://github.com/mdolab/baseclasses

extra:
  recipe-maintainers:
    - nwu63
    - eirikurj
    - whophil
